name = "aquarium-products"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "aquarium-db"
database_id = "75bd790a-c51a-441d-8d81-06dd83edd342"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "aquarium-db"
database_id = "75bd790a-c51a-441d-8d81-06dd83edd342"

[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "aquarium-db"
database_id = "75bd790a-c51a-441d-8d81-06dd83edd342"

[[r2_buckets]]
binding = "SUMMER_PROJECT"
bucket_name = "summer-project"