name = "aquarium-products"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "aquarium-db"
database_id = "75bd790a-c51a-441d-8d81-06dd83edd342"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "aquarium-db"
database_id = "75bd790a-c51a-441d-8d81-06dd83edd342"

[env.development]
[[env.development.d1_databases]]
binding = "DB"
database_name = "aquarium-db"
database_id = "75bd790a-c51a-441d-8d81-06dd83edd342"